repository: check-face/checkface
theme: jekyll-theme-cayman
title: Checkface
plugins:
    - jekyll-github-metadata
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jemoji
    - github-pages

markdown: kramdown